#!/bin/bash

FILES="`dirname $0`/files/"

sudo mkdir -p /etc/acpi/actions
sudo cp "$FILES/etc/acpi/actions/ac_adapter.sh" /etc/acpi/actions/
sudo cp "$FILES/etc/acpi/actions/lid.sh" /etc/acpi/actions/
sudo chmod 0755 /etc/acpi/actions/*

sudo mkdir -p /etc/acpi/events
sudo cp "$FILES/etc/acpi/events/ac_adapter" /etc/acpi/events/
sudo cp "$FILES/etc/acpi/events/lid" /etc/acpi/events/

sudo cp "$FILES/usr/share/pixmaps/wallpaper-arch.png" /usr/share/pixmaps/
[ ! -f /usr/share/pixmaps/wallpaper ] && sudo ln -sf /usr/share/pixmaps/wallpaper-arch.png /usr/share/pixmaps/wallpaper

sudo cp "$FILES/etc/DIR_COLORS" /etc/
sudo cp "$FILES/etc/lightdm/lightdm-gtk-greeter.conf" /etc/lightdm/

sudo mkdir -p /etc/NetworkManager/dispatcher.d
sudo cp "$FILES/etc/NetworkManager/dispatcher.d/50-packages" /etc/NetworkManager/dispatcher.d/
sudo chmod 0755 /etc/NetworkManager/dispatcher.d/50-packages
sudo cp "$FILES/etc/NetworkManager/dispatcher.d/90-open_captive_portal" /etc/NetworkManager/dispatcher.d/
sudo chmod 0755 /etc/NetworkManager/dispatcher.d/90-open_captive_portal

sudo cp "$FILES/home/bashrc" /root/.bashrc

sudo cp "$FILES/home/vimrc" /root/.vimrc

sudo cp "$FILES/usr/local/bin/energy-bias-hint" /usr/local/bin/
sudo cp "$FILES/usr/local/bin/lock-manager" /usr/local/bin/
sudo cp "$FILES/usr/local/bin/poweroff-manager" /usr/local/bin/
sudo cp "$FILES/usr/local/bin/screencast-manager" /usr/local/bin/
sudo cp "$FILES/usr/local/bin/screenshot-manager" /usr/local/bin/
sudo cp "$FILES/usr/local/bin/terminal" /usr/local/bin/
sudo cp "$FILES/usr/local/bin/urxvtq" /usr/local/bin/
sudo chmod 0755 /usr/local/bin/*

sudo cp "$FILES/usr/share/fonts/TTF/DejaVu Sans Mono Bold for Powerline.ttf" /usr/share/fonts/TTF/
sudo cp "$FILES/usr/share/fonts/TTF/DejaVu Sans Mono Bold Oblique for Powerline.ttf" /usr/share/fonts/TTF/
sudo cp "$FILES/usr/share/fonts/TTF/DejaVu Sans Mono for Powerline.ttf" /usr/share/fonts/TTF/
sudo cp "$FILES/usr/share/fonts/TTF/DejaVu Sans Mono Oblique for Powerline.ttf" /usr/share/fonts/TTF/
fc-cache -f

cp "$FILES/home/bashrc" ~/.bashrc

cp "$FILES/home/vimrc" ~/.vimrc

mkdir -p ~/.config/autostart
cp "$FILES/home/config/autostart/blueman.desktop" ~/.config/autostart/

cp "$FILES/home/gtkrc-2.0" ~/.gtkrc-2.0

mkdir -p ~/.config/gtk-3.0
cp "$FILES/home/config/gtk-3.0/settings.ini" ~/.config/gtk-3.0/
cp "$FILES/home/config/gtk-3.0/bookmarks" ~/.config/gtk-3.0/

mkdir -p ~/.config/conky
cp "$FILES/home/config/conky/conky.conf" ~/.config/conky/

cp "$FILES/home/config/chrome-flags.conf" ~/.config/

cp "$FILES/home/config/openbox/autostart" ~/.config/openbox/
sudo chmod 0755 ~/.config/openbox/autostart
cp "$FILES/home/config/openbox/environment" ~/.config/openbox/
sudo chmod 0755 ~/.config/openbox/environment
cp "$FILES/home/config/openbox/menu.xml" ~/.config/openbox/
cp "$FILES/home/config/openbox/rc.xml" ~/.config/openbox/

mkdir -p ~/.config/picom
cp "$FILES/home/config/picom/picom.conf" ~/.config/picom/

mkdir -p ~/.config/geany/colorschemes
cp "$FILES/home/config/geany/colorschemes/darcula.conf" ~/.config/geany/colorschemes/

cp "$FILES/home/config/mimeapps.list" ~/.config/

cp "$FILES/home/config/mpv/input.conf" ~/.config/mpv/
cp "$FILES/home/config/mpv/mpv.conf" ~/.config/mpv/

mkdir -p ~/.config/tint2
cp "$FILES/home/config/tint2/tint2panel" ~/.config/tint2/

mkdir -p ~/.config/viewnior
cp "$FILES/home/config/viewnior/viewnior.conf" ~/.config/viewnior/

mkdir -p ~/.config/xarchiver
cp "$FILES/home/config/xarchiver/xarchiverrc" ~/.config/xarchiver/

mkdir -p ~/.config/xfce4/xfconf/xfce-perchannel-xml
cp "$FILES/home/config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml" ~/.config/xfce4/xfconf/xfce-perchannel-xml/
cp "$FILES/home/config/xfce4/xfconf/xfce-perchannel-xml/thunar-volman.xml" ~/.config/xfce4/xfconf/xfce-perchannel-xml/

cp "$FILES/home/Xresources" ~/.Xresources

cp "$FILES/home/tmux.conf" ~/.tmux.conf

cp "$FILES/home/notify-osd" ~/.notify-osd

cp "$FILES/home/gmrunrc" ~/.gmrunrc

mkdir -p ~/.config/gsimplecal
cp "$FILES/home/config/gsimplecal/config" ~/.config/gsimplecal/

mkdir -p ~/.config/parcellite
cp "$FILES/home/config/parcellite/parcelliterc" ~/.config/parcellite/

mkdir -p ~/.config/zim
cp "$FILES/home/config/zim/preferences.conf" ~/.config/zim/

code --install-extension alefragnani.project-manager > /dev/null 2> /dev/null
code --install-extension christian-kohler.path-intellisense > /dev/null 2> /dev/null
code --install-extension dbaeumer.vscode-eslint > /dev/null 2> /dev/null
code --install-extension eg2.vscode-npm-script > /dev/null 2> /dev/null
code --install-extension esbenp.prettier-vscode > /dev/null 2> /dev/null
code --install-extension formulahendry.auto-close-tag > /dev/null 2> /dev/null
code --install-extension formulahendry.auto-rename-tag > /dev/null 2> /dev/null
code --install-extension kisstkondoros.vscode-gutter-preview > /dev/null 2> /dev/null
code --install-extension mikestead.dotenv > /dev/null 2> /dev/null
code --install-extension mrmlnc.vscode-pugbeautify > /dev/null 2> /dev/null
code --install-extension mrmlnc.vscode-scss > /dev/null 2> /dev/null
code --install-extension MS-CEINTL.vscode-language-pack-es > /dev/null 2> /dev/null
code --install-extension naumovs.color-highlight > /dev/null 2> /dev/null
code --install-extension naumovs.theme-oceanicnext > /dev/null 2> /dev/null
code --install-extension PKief.material-icon-theme > /dev/null 2> /dev/null
code --install-extension pmneo.tsimporter > /dev/null 2> /dev/null
code --install-extension quicktype.quicktype > /dev/null 2> /dev/null
code --install-extension rangav.vscode-thunder-client > /dev/null 2> /dev/null
code --install-extension Rubymaniac.vscode-paste-and-indent > /dev/null 2> /dev/null
code --install-extension ryanolsonx.solarized > /dev/null 2> /dev/null
code --install-extension usernamehw.errorlens > /dev/null 2> /dev/null
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples > /dev/null 2> /dev/null
code --install-extension VisualStudioExptTeam.vscodeintellicode > /dev/null 2> /dev/null
code --install-extension wayou.vscode-todo-highlight > /dev/null 2> /dev/null
code --install-extension zhuangtongfa.material-theme > /dev/null 2> /dev/null
code --install-extension Zignd.html-css-class-completion > /dev/null 2> /dev/null
mkdir -p ~/.config/Code/User
cp "$FILES/home/config/Code/User/settings.json" ~/.config/Code/User/
cp "$FILES/home/config/Code/User/keybindings.json" ~/.config/Code/User/
