#!/bin/sh

function notify() {
	local display=":$(ls /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"
	local user=$(who | grep '('$display')' | awk '{print $1}' | head -n 1)
	local uid=$(id -u $user)
	sudo -u $user DISPLAY=$display DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus notify-send "$@"
}

if [ "$2" = "up" ]; then
	MUST_UPDATE=`find /etc/pacman.d -maxdepth 1 -type f -name mirrorlist -mtime +1 -printf '.' | wc -c`

	if [ $MUST_UPDATE -eq 1 ]; then
		systemctl start reflector
		notify -i software "Reflector" "Se ha optimizado la lista de mirrors para la descarga de software."
		sleep 5
		pkgfile --update
		notify -i terminal "pkgfile" "Se ha actualizado la lista de paquetes disponibles en los repositorios de software."
	fi
fi
